package com.android.predict.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PackageName = new Property(1, String.class, "packageName", false, "PACKAGENAME");
        public final static Property Date = new Property(2, long.class, "date", false, "DATE");
        public final static Property WifiConnect = new Property(3, boolean.class, "wifiConnect", false, "WIFICONNECT");
        public final static Property MobileConnect = new Property(4, boolean.class, "mobileConnect", false, "mobileconnect");
        public final static Property Latitude = new Property(5, double.class, "latitude", false, "LATITUDE");
        public final static Property Longtitude = new Property(6, double.class, "longtitude", false, "LONGTITUDE");
        public final static Property IsFebruary = new Property(7, boolean.class, "isFebruary", false, "ISFEBRUARY");
        public final static Property IsSpring = new Property(8, boolean.class, "isSpring", false, "ISSPRING");
        public final static Property IsSummer = new Property(9, boolean.class, "isSummer", false, "ISSUMMER");
        public final static Property IsAutumn = new Property(10, boolean.class, "isAutumn", false, "ISAUTUMN");
        public final static Property IsWinter = new Property(11, boolean.class, "isWinter", false, "ISWINTER");
        public final static Property IsMatinal = new Property(12, boolean.class, "isMatinal", false, "ISMATINAL");
        public final static Property IsMorning = new Property(13, boolean.class, "isMorning", false, "ISMORNING");
        public final static Property IsNoon = new Property(14, boolean.class, "isNoon", false, "ISNOON");
        public final static Property IsAfternoon = new Property(15, boolean.class, "isAfternoon", false, "ISAFTERNOON");
        public final static Property IsEvening = new Property(16, boolean.class, "isEvening", false, "ISEVENING");
        public final static Property IsNight = new Property(17, boolean.class, "isNight", false, "ISNIGHT");
        public final static Property IsBeginOfMouth = new Property(18, boolean.class, "isBeginOfMouth", false, "ISBEGINOFMOUTH");
        public final static Property IsEndOfMouth = new Property(19, boolean.class, "isEndOfMouth", false, "ISENDOFMOUTH");
        public final static Property IsWeekend = new Property(20, boolean.class, "isWeekend", false, "ISWEEKEND");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PACKAGENAME\" TEXT," + // 1: packageName
                "\"DATE\" INTEGER NOT NULL ," + // 2: date
                "\"WIFICONNECT\" INTEGER NOT NULL ," + // 3: wifiConnect
                "\"mobileconnect\" INTEGER NOT NULL ," + // 4: mobileConnect
                "\"LATITUDE\" REAL NOT NULL ," + // 5: latitude
                "\"LONGTITUDE\" REAL NOT NULL ," + // 6: longtitude
                "\"ISFEBRUARY\" INTEGER NOT NULL ," + // 7: isFebruary
                "\"ISSPRING\" INTEGER NOT NULL ," + // 8: isSpring
                "\"ISSUMMER\" INTEGER NOT NULL ," + // 9: isSummer
                "\"ISAUTUMN\" INTEGER NOT NULL ," + // 10: isAutumn
                "\"ISWINTER\" INTEGER NOT NULL ," + // 11: isWinter
                "\"ISMATINAL\" INTEGER NOT NULL ," + // 12: isMatinal
                "\"ISMORNING\" INTEGER NOT NULL ," + // 13: isMorning
                "\"ISNOON\" INTEGER NOT NULL ," + // 14: isNoon
                "\"ISAFTERNOON\" INTEGER NOT NULL ," + // 15: isAfternoon
                "\"ISEVENING\" INTEGER NOT NULL ," + // 16: isEvening
                "\"ISNIGHT\" INTEGER NOT NULL ," + // 17: isNight
                "\"ISBEGINOFMOUTH\" INTEGER NOT NULL ," + // 18: isBeginOfMouth
                "\"ISENDOFMOUTH\" INTEGER NOT NULL ," + // 19: isEndOfMouth
                "\"ISWEEKEND\" INTEGER NOT NULL );"); // 20: isWeekend
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(2, packageName);
        }
        stmt.bindLong(3, entity.getDate());
        stmt.bindLong(4, entity.getWifiConnect() ? 1L: 0L);
        stmt.bindLong(5, entity.getMobileConnect() ? 1L: 0L);
        stmt.bindDouble(6, entity.getLatitude());
        stmt.bindDouble(7, entity.getLongtitude());
        stmt.bindLong(8, entity.getIsFebruary() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsSpring() ? 1L: 0L);
        stmt.bindLong(10, entity.getIsSummer() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsAutumn() ? 1L: 0L);
        stmt.bindLong(12, entity.getIsWinter() ? 1L: 0L);
        stmt.bindLong(13, entity.getIsMatinal() ? 1L: 0L);
        stmt.bindLong(14, entity.getIsMorning() ? 1L: 0L);
        stmt.bindLong(15, entity.getIsNoon() ? 1L: 0L);
        stmt.bindLong(16, entity.getIsAfternoon() ? 1L: 0L);
        stmt.bindLong(17, entity.getIsEvening() ? 1L: 0L);
        stmt.bindLong(18, entity.getIsNight() ? 1L: 0L);
        stmt.bindLong(19, entity.getIsBeginOfMouth() ? 1L: 0L);
        stmt.bindLong(20, entity.getIsEndOfMouth() ? 1L: 0L);
        stmt.bindLong(21, entity.getIsWeekend() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(2, packageName);
        }
        stmt.bindLong(3, entity.getDate());
        stmt.bindLong(4, entity.getWifiConnect() ? 1L: 0L);
        stmt.bindLong(5, entity.getMobileConnect() ? 1L: 0L);
        stmt.bindDouble(6, entity.getLatitude());
        stmt.bindDouble(7, entity.getLongtitude());
        stmt.bindLong(8, entity.getIsFebruary() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsSpring() ? 1L: 0L);
        stmt.bindLong(10, entity.getIsSummer() ? 1L: 0L);
        stmt.bindLong(11, entity.getIsAutumn() ? 1L: 0L);
        stmt.bindLong(12, entity.getIsWinter() ? 1L: 0L);
        stmt.bindLong(13, entity.getIsMatinal() ? 1L: 0L);
        stmt.bindLong(14, entity.getIsMorning() ? 1L: 0L);
        stmt.bindLong(15, entity.getIsNoon() ? 1L: 0L);
        stmt.bindLong(16, entity.getIsAfternoon() ? 1L: 0L);
        stmt.bindLong(17, entity.getIsEvening() ? 1L: 0L);
        stmt.bindLong(18, entity.getIsNight() ? 1L: 0L);
        stmt.bindLong(19, entity.getIsBeginOfMouth() ? 1L: 0L);
        stmt.bindLong(20, entity.getIsEndOfMouth() ? 1L: 0L);
        stmt.bindLong(21, entity.getIsWeekend() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // packageName
            cursor.getLong(offset + 2), // date
            cursor.getShort(offset + 3) != 0, // wifiConnect
            cursor.getShort(offset + 4) != 0, // mobileConnect
            cursor.getDouble(offset + 5), // latitude
            cursor.getDouble(offset + 6), // longtitude
            cursor.getShort(offset + 7) != 0, // isFebruary
            cursor.getShort(offset + 8) != 0, // isSpring
            cursor.getShort(offset + 9) != 0, // isSummer
            cursor.getShort(offset + 10) != 0, // isAutumn
            cursor.getShort(offset + 11) != 0, // isWinter
            cursor.getShort(offset + 12) != 0, // isMatinal
            cursor.getShort(offset + 13) != 0, // isMorning
            cursor.getShort(offset + 14) != 0, // isNoon
            cursor.getShort(offset + 15) != 0, // isAfternoon
            cursor.getShort(offset + 16) != 0, // isEvening
            cursor.getShort(offset + 17) != 0, // isNight
            cursor.getShort(offset + 18) != 0, // isBeginOfMouth
            cursor.getShort(offset + 19) != 0, // isEndOfMouth
            cursor.getShort(offset + 20) != 0 // isWeekend
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPackageName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDate(cursor.getLong(offset + 2));
        entity.setWifiConnect(cursor.getShort(offset + 3) != 0);
        entity.setMobileConnect(cursor.getShort(offset + 4) != 0);
        entity.setLatitude(cursor.getDouble(offset + 5));
        entity.setLongtitude(cursor.getDouble(offset + 6));
        entity.setIsFebruary(cursor.getShort(offset + 7) != 0);
        entity.setIsSpring(cursor.getShort(offset + 8) != 0);
        entity.setIsSummer(cursor.getShort(offset + 9) != 0);
        entity.setIsAutumn(cursor.getShort(offset + 10) != 0);
        entity.setIsWinter(cursor.getShort(offset + 11) != 0);
        entity.setIsMatinal(cursor.getShort(offset + 12) != 0);
        entity.setIsMorning(cursor.getShort(offset + 13) != 0);
        entity.setIsNoon(cursor.getShort(offset + 14) != 0);
        entity.setIsAfternoon(cursor.getShort(offset + 15) != 0);
        entity.setIsEvening(cursor.getShort(offset + 16) != 0);
        entity.setIsNight(cursor.getShort(offset + 17) != 0);
        entity.setIsBeginOfMouth(cursor.getShort(offset + 18) != 0);
        entity.setIsEndOfMouth(cursor.getShort(offset + 19) != 0);
        entity.setIsWeekend(cursor.getShort(offset + 20) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
